package launcher.wb.codegeneration

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSPropertyDeclaration
import com.google.devtools.ksp.symbol.KSType
import com.google.devtools.ksp.symbol.Modifier
import com.google.devtools.ksp.validate
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.asClassName
import wb.bean.ABTestKeyExclude
import wb.bean.ABTestKeys
import wb.service.IProvider

/**
 * 佛祖保佑         永无BUG
 *
 * @author Created by joker on 2026/5/20
 *
 * ABTestKeys 注解处理器。
 *
 * 扫描 @ABTestKeys 标注的类/object，收集所有 String 类型属性（排除 @ABTestKeyExclude 标注的），
 * 生成顶层函数 `{ClassName}_getAllAbKeys(): List<String>`。
 *
 * 当 generateProvider = true 时，额外生成 AbTestProvider 实现类并通知 ServiceAggregatorGeneration 注册。
 */
class ABTestKeysGeneration(
    codeGenerator: CodeGenerator,
    logger: KSPLogger
) : BaseGeneration(codeGenerator, logger) {

    companion object {
        /** @ABTestKeys 全限定名 */
        private val ABTESTKEYS_ANNOTATION_NAME = ABTestKeys::class.qualifiedName!!

        /** @ABTestKeyExclude 全限定名 */
        private val EXCLUDE_ANNOTATION_NAME = ABTestKeyExclude::class.qualifiedName!!

        /** AbTestProvider 接口包路径 */
        private const val AB_TEST_PROVIDER_PACKAGE = "com.webull.commonmodule.abtest"

        /** AbTestProvider 接口类名 */
        private const val AB_TEST_PROVIDER_NAME = "AbTestProvider"

        /** ServiceAggregator 注册的目标接口全限定名 */
        private val SERVICE_INTERFACE = IProvider::class.qualifiedName!!
    }

    /** ServiceAggregatorGeneration 引用，由 WbKspProcessor 注入 */
    var serviceAggregator: ServiceAggregatorGeneration? = null

    private val collectedClasses = mutableListOf<CollectedClassInfo>()

    override fun collect(resolver: Resolver): List<KSAnnotated> {
        val unprocessed = mutableListOf<KSAnnotated>()

        resolver.getSymbolsWithAnnotation(ABTestKeys::class.qualifiedName!!).forEach { symbol ->
            if (!symbol.validate()) {
                unprocessed += symbol
                return@forEach
            }
            if (symbol is KSClassDeclaration) {
                val generateProvider = extractGenerateProvider(symbol)
                collectedClasses += CollectedClassInfo(symbol, generateProvider)
            }
        }

        return unprocessed
    }

    override fun hasDataToGenerate(): Boolean = collectedClasses.isNotEmpty()

    override fun generate() {
        for (info in collectedClasses) {
            generateForClass(info)
        }
    }

    private fun generateForClass(info: CollectedClassInfo) {
        val classDecl = info.classDecl
        val packageName = classDecl.packageName.asString()
        val simpleName = classDecl.simpleName.asString()

        // 收集所有 String 类型属性及其注释，排除 @ABTestKeyExclude 标注的
        val properties = collectStringProperties(classDecl)

        if (properties.isEmpty()) {
            logger.warn("ABTestKeys: $simpleName has no String properties to collect")
            return
        }

        logger.info("ABTestKeys: Generating ${simpleName}_getAllAbKeys() with ${properties.size} keys")

        val fileName = "${simpleName}_AbKeys"
        val functionName = "${simpleName}_getAllAbKeys"

        // 构建 listOf(...) 内容，每个 key 带行内注释
        val listEntries = properties.mapIndexed { index, (propName, comment) ->
            val comma = if (index < properties.size - 1) "," else ""
            if (comment.isNotEmpty()) {
                "$simpleName.$propName$comma // $comment"
            } else {
                "$simpleName.$propName$comma"
            }
        }.joinToString("\n    ")

        val containingFile = classDecl.containingFile
        val dependencies = if (containingFile != null) {
            Dependencies(aggregating = false, containingFile)
        } else {
            Dependencies(aggregating = false)
        }

        // 生成 getAllAbKeys 顶层函数
        val keysFileSpec = FileSpec.builder(packageName, fileName)
            .addFileComment("Generated by ABTestKeys KSP processor. Do not modify!")
            .addFunction(
                FunSpec.builder(functionName)
                    .addKdoc("Auto-generated ABTest keys for [%L].\n", simpleName)
                    .addKdoc("\n")
                    .addKdoc("@return all ABTest keys defined in [%L], total %L keys.\n", simpleName, properties.size)
                    .returns(List::class.asClassName().parameterizedBy(String::class.asClassName()))
                    .addStatement("return listOf(\n    $listEntries\n)")
                    .build()
            )
            .build()

        writeKotlinFile(keysFileSpec, dependencies)

        // 如果 generateProvider = true，生成 Provider 类并注册
        if (info.generateProvider) {
            generateProvider(classDecl, packageName, simpleName, functionName, dependencies)
        }
    }

    /**
     * 生成 AbTestProvider 实现类并注册到 ServiceAggregator。
     *
     * 生成代码：
     * ```kotlin
     * class TradeCommonABTestKey_AbTestProvider : AbTestProvider {
     *     override fun keys(): List<String> = TradeCommonABTestKey_getAllAbKeys()
     * }
     * ```
     */
    private fun generateProvider(
        sourceClassDecl: KSClassDeclaration,
        packageName: String,
        keyClassName: String,
        getAllAbKeysFunctionName: String,
        dependencies: Dependencies
    ) {
        val providerClassName = "${keyClassName}_AbTestProvider"
        val abTestProviderInterface = ClassName(AB_TEST_PROVIDER_PACKAGE, AB_TEST_PROVIDER_NAME)

        val providerTypeSpec = TypeSpec.classBuilder(providerClassName)
            .addSuperinterface(abTestProviderInterface)
            .addFunction(
                FunSpec.builder("keys")
                    .addModifiers(KModifier.OVERRIDE)
                    .returns(List::class.asClassName().parameterizedBy(String::class.asClassName()))
                    .addStatement("return %L()", getAllAbKeysFunctionName)
                    .build()
            )
            .build()

        val providerFileSpec = FileSpec.builder(packageName, providerClassName)
            .addFileComment("Generated by ABTestKeys KSP processor. Do not modify!")
            .addType(providerTypeSpec)
            .build()

        writeKotlinFile(providerFileSpec, dependencies)

        // 通知 ServiceAggregatorGeneration 注册此 Provider
        val providerFullClassName = ClassName(packageName, providerClassName)
        serviceAggregator?.addExternalRegistration(SERVICE_INTERFACE, providerFullClassName, sourceClassDecl)
            ?: logger.warn("ABTestKeys: ServiceAggregatorGeneration not available, Provider $providerClassName won't be auto-registered")
    }

    /**
     * 从 @ABTestKeys 注解中提取 generateProvider 参数值
     */
    private fun extractGenerateProvider(classDecl: KSClassDeclaration): Boolean {
        val annotation = classDecl.annotations.firstOrNull {
            it.annotationType.resolve().declaration.qualifiedName?.asString() == ABTESTKEYS_ANNOTATION_NAME
        } ?: return false

        return annotation.arguments.firstOrNull {
            it.name?.asString() == ABTestKeys::generateProvider.name
        }?.value as? Boolean ?: false
    }

    /**
     * 收集类中所有 String 类型的属性名及其注释，排除标注了 @ABTestKeyExclude 的。
     *
     * 支持：
     * - Kotlin object 的 val 属性
     * - Java class 的 public static final String 字段
     *
     * @return List of Pair(propertyName, comment)
     */
    private fun collectStringProperties(classDecl: KSClassDeclaration): List<Pair<String, String>> {
        val result = mutableListOf<Pair<String, String>>()

        // getAllProperties() 适用于 Kotlin 和 Java
        val allProperties = classDecl.getAllProperties().toList()

        for (property in allProperties) {
            if (!isStringProperty(property)) continue
            if (hasExcludeAnnotation(property)) continue
            if (Modifier.PRIVATE in property.modifiers) continue

            val comment = extractComment(property)
            result += property.simpleName.asString() to comment
        }

        // 如果没有结果，尝试从 declarations 中获取（兜底 Java static 字段）
        if (result.isEmpty()) {
            val declaredProperties = classDecl.declarations
                .filterIsInstance<KSPropertyDeclaration>()
                .toList()

            for (property in declaredProperties) {
                if (!isStringProperty(property)) continue
                if (hasExcludeAnnotation(property)) continue
                if (Modifier.PRIVATE in property.modifiers) continue

                val comment = extractComment(property)
                result += property.simpleName.asString() to comment
            }

            // 如果仍然没有结果，记录详细日志帮助排查
            if (result.isEmpty()) {
                logger.warn("ABTestKeys: ${classDecl.simpleName.asString()} - getAllProperties count: ${allProperties.size}, declarations(property) count: ${declaredProperties.size}")
                for (prop in declaredProperties.take(3)) {
                    val type = prop.type.resolve().declaration.qualifiedName?.asString()
                    logger.warn("ABTestKeys:   property '${prop.simpleName.asString()}' type=$type modifiers=${prop.modifiers}")
                }
            }
        }

        return result
    }

    private fun isStringProperty(property: KSPropertyDeclaration): Boolean {
        val resolvedType = property.type.resolve()
        val typeQualifiedName = resolvedType.declaration.qualifiedName?.asString()
        return typeQualifiedName == String::class.qualifiedName || typeQualifiedName == java.lang.String::class.java.name
    }

    private fun extractComment(property: KSPropertyDeclaration): String {
        val docString = property.docString ?: return ""
        return docString.lines()
            .map { it.trim().removePrefix("*").trim() }
            .firstOrNull { it.isNotEmpty() }
            ?: ""
    }

    private fun hasExcludeAnnotation(property: KSPropertyDeclaration): Boolean {
        return property.annotations.any { annotation ->
            annotation.annotationType.resolve().declaration.qualifiedName?.asString() == EXCLUDE_ANNOTATION_NAME
        }
    }

    private data class CollectedClassInfo(
        val classDecl: KSClassDeclaration,
        val generateProvider: Boolean
    )
}
