apply plugin: 'kotlin'

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation 'com.squareup:kotlinpoet:1.18.1'
    implementation 'com.google.devtools.ksp:symbol-processing-api:2.0.21-1.0.28'
    implementation project(':EventAnnotation')
}

kotlin {
    jvmToolchain(17)
}

java {
    withSourcesJar()
}
